export const defaultLanguage = 'en';

export const siteContent = {
  en: {
    navigation: {
      home: 'Home',
      tours: 'Tours',
      reviews: 'Reviews',
      about: 'About',
      contact: 'Contact',
    },
    actions: {
      bookWhatsApp: 'Book on WhatsApp',
      viewTours: 'View tour options',
      tourDetails: 'Tour details',
      book: 'Book',
      planTrip: 'Plan a Lombok trip',
      shareReview: 'Share your experience',
      consultItinerary: 'Talk through your itinerary',
    },
    home: {
      heroKicker: 'PRIVATE TOURS & TRANSPORT IN LOMBOK',
      heroTitle: 'Explore Lombok at your own pace.',
      heroText: 'Plan a private tour, island-hopping day, or custom route with a local team from Gerupuk. Tell us what you have in mind, and we will help you shape the day around it.',
      basedIn: 'Based in Gerupuk',
      local: 'Local',
      localDetail: 'Lombok team',
      private: 'Private',
      privateDetail: 'Flexible routes',
      available: 'Available daily',
      availableDetail: '08.00–21.00',
      planningKicker: 'Make the day feel like your own.',
      planningTitle: 'Spend less time figuring out the route, and more time enjoying Lombok.',
      features: [
        ['fa-route', 'A route that fits your time', 'Tell us how long you have and what you would like to see. We will help you put together a day that makes sense.'],
        ['fa-car-side', 'Comfortable transport between stops', 'Travel between destinations with a clean vehicle and a local driver who knows the roads around Lombok.'],
        ['fa-headset', 'Clear communication from the start', 'Talk through your plans before you go, and reach out to our team when you need help during the trip.'],
      ],
      aboutKicker: 'From Gerupuk, for your time in Lombok.',
      aboutTitle: 'More than a ride, a better way to plan the day.',
      aboutText: 'Fin Transport and Tour helps you arrange transport, destinations, and timing before your travel day. You decide how you want to travel, and we help make the plan easier to follow.',
      toursKicker: 'Choose a trip, then make it your own.',
      toursTitle: 'Find your way around Lombok.',
      toursText: 'Every option is a private trip, so you can talk through the route before you leave.',
      reviewsKicker: 'Stories from guests who have travelled with us.',
      reviewsTitle: 'The kind of trip guests remember fondly.',
      ratingLabel: '5 out of 5 stars',
    },
    footer: {
      description: 'A local partner for Lombok tours, vehicle rental, and custom itineraries.',
      navigation: 'Navigate',
      contact: 'Contact',
      tours: 'Tour options',
      reviews: 'Guest reviews',
      about: 'About us',
      copyright: 'All rights reserved.',
    },
    tour: {
      privateTrip: 'private trip',
      notFound: 'Tour not found',
      backHome: 'Back to the homepage',
      backToTours: 'All tour options',
      photo: 'View photo',
      experience: 'PRIVATE LOMBOK TRIP',
      duration: 'DURATION',
      fullDay: 'Full-day trip',
      tripType: 'TRIP TYPE',
      privateGroup: 'Private group',
      startingFrom: 'STARTING FROM',
      priceNote: 'Price may vary based on\ngroup size',
      bookingNote: 'Admin replies daily, 08.00–21.00 WITA',
      includesKicker: 'YOUR TRIP INCLUDES',
      includesTitle: 'What is included',
      itineraryKicker: 'DAY PLAN',
      itineraryTitle: 'Your itinerary',
      helpKicker: 'NOT SURE WHICH TOUR FITS YOUR PLANS?',
      helpTitle: 'Talk through your Lombok trip with us.',
    },
    floating: {
      whatsappLabel: 'Book a Lombok trip on WhatsApp',
      scrollTopLabel: 'Scroll back to the top',
      bookingMessage: "Hello, I'm interested in booking a Lombok trip. Could I get more information?",
    },
  },
};

export const copy = siteContent[defaultLanguage];
